site_name: My Learnings
site_url: https://docs.anandas.in
site_author: Ananda S
site_description: "My Learnings - compiled by Ananda S"
repo_url: "https://github.com/asarangaram/docs.anandas.in"
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides

nav:
  - 'index.md'
  - Linux Tools:
    - 'crontab.md'
    - 'dd.md'
    
