# Project information
site_name: My Learnings
site_url: https://docs.anandas.in
site_author: Ananda S
site_description: "Today I Learned (TIL) on Tech"
repo_url: "https://github.com/asarangaram/docs.anandas.in"
edit_uri: "edit/main/docs/"

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags
  - exclude:
      glob:
        - "content/concepts/ai_ml_basics/decision_making.md"
        - content/concepts/ai_ml_basics/approaches.md
        - content/concepts/ai_ml_basics/cognitive_functions.md
        - content/concepts/ai_ml_basics/tasks.md  
        - content/concepts/ai_ml_basics/ann.md

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: asarangaram
      repo: docs.anandas.in
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - about:
    - index.md
  - linux-admin:
    - content/linux-admin/crontab.md
    - content/linux-admin/manage_users.md
    - content/linux-admin/ports.md
    - content/linux-admin/runscript_without_password.md
    - content/linux-admin/sd_card_backup_with_dd.md
    - content/linux-admin/mermaid.md
    - content/linux-admin/mime.md
    - content/linux-admin/notify-send.md
    - content/linux-admin/packages.md
    - content/linux-admin/vscode.md
    - content/linux-admin/fdisk.md
    - content/linux-develop/vim.md
  - linux-develop:
    - content/linux-develop/git.md
    - content/linux-develop/markdown.md
    - content/linux-develop/postman.md
    - content/linux-develop/tmux.md
    - content/linux-develop/hugo.md
  - linux-infra:
    - nginx: content/linux-infra/Nginx.md
    - postgresql: content/linux-infra/postgresql.md
    - mddm: content/linux-infra/mdadm.md
    - my_sql: content/linux-infra/mysql.md
    - redis: content/linux-infra/redis.md
    - image_magick: content/linux-infra/image_magick.md
    - image_utils: content/linux-infra/image_utilities.md
    
  - embedded:
    - m5_stack:
      - content/embedded/m5_stack/index.md
      - content/embedded/m5_stack/HomeBrew_Basics.md
      - content/embedded/m5_stack/m5_stick_setup.md
      - content/embedded/m5_stack/nutx.md
    - Raspberry Pi:
      - content/embedded/Raspberry Pi/Setup_RPi.md
      - content/embedded/Raspberry Pi/Lychee_on_RPi.md
      - content/embedded/Raspberry Pi/Lychee_as_photo_manager.md
  - python:
    - content/python/schedule.md
    - content/python/pillow.md
    - content/python/using pip.md
    - content/python/scripts/validate_password.md
    - content/python/scripts/single_instance_lock.md
    - Image Repo as a Flask Microservice:
      - content/python/Image Repo as a Flask Microservice/Installation.md
      - content/python/Image Repo as a Flask Microservice/first_flask_app.md
      - content/python/Image Repo as a Flask Microservice/image_upload_endpoint.md
      - content/python/Image Repo as a Flask Microservice/index.md

  - concepts:
    - content/concepts/image_dithering.md
    - content/FAQ/REST.md 
    - content/concepts/MkDocs.md   
    - Building Artificial Intelligence using Machine Learning:
      - content/concepts/ai_ml_basics/index.md
    
  - faq: content/FAQ/index.md 
  - glossary: content/linux-infra/glossary.md
  - help:
    - content/features_demo/feature_demo.md

