[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "My Learnings"
authors = [{name = "Ananda S", email = "asarangaram@gmail.com"}]
dynamic = ["version", "description"]
